### ISSUE TITLE
error not returning properly when async request fails

### ISSUE THREAD

**Issue by bcorrigeux** [dvonthenen/symbl-go-sdk#90]
## Bug Report

im trying to run GetAudioSummaryUI() and when everything goes well it works great but when there is an issue im not getting the error back and just receiving an empty struct.
Based on the logs it looks like the cast here is failing and causing the error to get dropped. guessing this could be an issue other places in the code but i have not attempted any others yet

## Expected Behavior

nil, error is returned giving the error from the underlying function

## Steps to Reproduce the Bug

run a request to GetAudioSummaryUi with an invalid argument for AudioUrl

## Screenshots or additional information and context

it looks like the the typecast is failing so the status code is never checked

`	err = c.Client.Do(ctx, req, &result)

	if e, ok := err.(*interfaces.StatusError); ok {
		if e.Resp.StatusCode != http.StatusOK {
			klog.V(1).Infof("HTTP Code: %v\n", e.Resp.StatusCode)
			klog.V(6).Infof("async.GetAudioSummaryUI LEAVE\n")
			return nil, err
		}
	}
`

I0622 14:40:37.093373   49900 summaryui.go:153] Calling https://api.symbl.ai/v1/conversations/6185037678772224/experiences?
I0622 14:40:37.093433   49900 rest.go:685] rest.Do ENTER
I0622 14:40:37.093445   49900 rest.go:698] Content-Type = application/json
I0622 14:40:37.472604   49900 rest.go:713] HTTP Error Code: 400
I0622 14:40:37.472699   49900 rest.go:720] rest.Do LEAVE
I0622 14:40:37.472740   49900 rest.go:751] err = c.Client.Do failed. Err: 400 Bad Request: {"message":"No file available at this location: https://s3_bucket.s3.us-east-2.amazonaws.com/file_here"}
I0622 14:40:37.472782   49900 rest.go:752] rest.Do LEAVE
I0622 14:40:37.472799   49900 summaryui.go:182] GET AudioSummaryUI succeeded
I0622 14:40:37.472838   49900 summaryui.go:183] async.GetAudioSummaryUI LEAVE
&{Name: URL:}

**Comment by dvonthenen** [comment]
Thanks for filing this issue. Will be taking a look at this today!
